VIDEO-8190: Update toolchain image and fix boost builds (#28)
* Use tags instead of releases to auto-detect latest boost version

- boostorg/boost uses tags instead of releases, the script was incorrectly trying to parse the boost version by fetching releases instead of tags, leading to build failures for all regular builds

* Use new build executors

- use buildtools version 17 for linux and android
- use xcode 12.5.1 to build for darwin and iOS
- use macos gen2 for iOS and darwin
- use YAML compliant syntax for multiple merge anchors
- use small/medium+ resources for linux/android builds
- parameterize xcode version and use it in the Circle CI cache keys

* Remove arm_gnueabihf and i386 architectures for linux builds

- remove 32-bit option from linux intel builds
- remove arm build for linux
- remove arm configuration for linux

* Other Circle CI config enhancements:
- store build staging log files as artifacts for linux and android builds
- refactor to use build matrix
- don't use cache for mac builds (not worth it)
- don't update brew before installing Mac dependencies (Circle already keeps the Mac images reasonably up-to-date)
- add validation when parsing tag
- remove unused aliases
- make boost-libs a pipeline parameter

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,111 +1,96 @@
 version: 2.1
 
+parameters:
+  boost-libs:
+    description: "List of boost libraries to build"
+    type: string
+    # We removed serialization as we need to be able to build for iOS 9 and there are code that is using iOS 10+ features
+    default: "atomic context coroutine date_time exception iostreams program_options random regex system test thread"
+
+  xcode-version:
+    description: Xcode version for iOS and Darwin builds
+    type: string
+    default: "12.5.1"
+
+  twilio-video-sdk-toolchain-image:
+    description: twilio-video-sdk-toolchain docker image to use for linux and android
+    type: string
+    default: "twilio/twilio-video-sdk-toolchain:17"
+
 aliases:
   - &workspace
     ~/twilio-boost-build
-  - &build_output
-    ~/twilio-boost-build/target/output
+
   - ignore-master: &ignore-master
       filters:
         tags:
           only: /.*/
         branches:
           ignore: /^master/
+
   - only-release-tags: &only-release-tags
       filters:
         tags:
           only: /^release-.*/
         branches:
           ignore: /.*/
-  - platform-parameter: &platform-parameter
-      platform:
-        description: "Platform to build"
-        type: enum
-        enum: ["headers", "android", "linux", "linux-cxx11-abi-disabled", "ios", "osx"]
-  - boost-libs-parameter: &boost-libs-parameter
-      boost-libs:
-        description: "List of boost libraries to build"
-        type: string
-        # We removed serialization as we need to be able to build for iOS 9 and there are code that is using iOS 10+ features
-        default: "atomic context coroutine date_time exception iostreams program_options random regex system test thread"
-  - pre-steps-parameter: &pre-steps-parameter
-      pre-steps:
-        description: "Steps that will be executed before build starts"
-        type: steps
-        default: []
-  - post-steps-parameter: &post-steps-parameter
-      post-steps:
-        description: "Steps that will be executed after build ends"
-        type: steps
-        default: []
-  - build-steps-parameter: &build-steps-parameter
-      build-steps:
-        description: "Steps that will be executed as main build target"
-        type: steps
 
 executors:
   linux-executor:
+    parameters:
+      resource-class:
+        type: enum
+        enum: [small, medium, medium+, large, xlarge]
+        default: medium+
     docker:
-      - image: cibuilderbot/docker-circleci-linux-android
+      - image: << pipeline.parameters.twilio-video-sdk-toolchain-image >>
         auth:
           username: $DOCKER_HUB_USERNAME
           password: $DOCKER_HUB_PASSWORD
-    resource_class: xlarge
+    resource_class: << parameters.resource-class >>
     working_directory: *workspace
     environment:
       CMAKE_BUILD_PARALLEL_LEVEL: 2
-  android-executor:
-    docker:
-      - image: twilio/twilio-video-sdk-toolchain:16
-        auth:
-          username: $DOCKER_HUB_USERNAME
-          password: $DOCKER_HUB_PASSWORD
-    resource_class: xlarge
-    working_directory: *workspace
-    environment:
-      CMAKE_BUILD_PARALLEL_LEVEL: 2
-  macos-ios-executor:
+
+  mac-executor:
     macos:
-      xcode: "12.2.0"
-    resource_class: large
+      xcode: << pipeline.parameters.xcode-version >>
+    resource_class: macos.x86.medium.gen2
     working_directory: *workspace
 
 commands:
   generate_build_settings:
-    description: "Generate build env variables"
+    description: "Parse tag to determine boost version and twilio suffix"
     steps:
       - run:
-          name: Make env variables from build tag
+          name: Parse build tag
           command: |
             if [ -z "$CIRCLE_TAG" ]; then
               echo "Must use release tag to build boost releases. Push \`release-1.71.0-twilio3\`-style tag to trigger."
-              touch $BASH_ENV
+              echo "Will attempt to build with the latest boost version."
             else
-              echo 'export BOOST_VERSION=$(echo $CIRCLE_TAG | cut -d - -f 2)' >> $BASH_ENV
-              echo 'export TWILIO_SUFFIX=$(echo $CIRCLE_TAG | cut -d - -f 3)' >> $BASH_ENV
+              BOOST_VERSION=$(echo $CIRCLE_TAG | cut -d - -f 2)
+              if [[ "$BOOST_VERSION" == "" ]]; then
+                echo "Failed to parse boost version from tag: $CIRCLE_TAG"
+                echo "Expected format: \`release-1.71.0-twilio3\`"
+                exit 1
+              fi
+              echo BOOST_VERSION=$BOOST_VERSION
+
+              TWILIO_SUFFIX=$(echo $CIRCLE_TAG | cut -d - -f 3)
+              echo TWILIO_SUFFIX=$TWILIO_SUFFIX
+
+              echo "export BOOST_VERSION=$BOOST_VERSION" >> $BASH_ENV
+              echo "export TWILIO_SUFFIX=$TWILIO_SUFFIX" >> $BASH_ENV
             fi
 
-  prepare_macos_ios:
-    description: "Prepare environment for MacOS and iOS builds (cache enabled)"
-    parameters:
-      cache-tag:
-        description: "Cache tag"
-        type: string
+  install_mac_buildtools:
+    description: "Prepare environment for MacOS and iOS builds"
     steps:
-      - restore_cache:
-          keys:
-            - v4-homebrew-<< parameters.cache-tag >>-{{ checksum ".circleci/config.yml" }}
       - run:
-          name: "Install necessary components through Homebrew"
+          name: "Run brew install"
           command: |
-            brew update
-            brew install maven
-            brew install boost-bcp
-            brew install rsync
-      - save_cache:
-          key: v4-homebrew-<< parameters.cache-tag >>-{{ checksum ".circleci/config.yml" }}
-          paths:
-            - /usr/local/Homebrew
+            HOMEBREW_NO_AUTO_UPDATE=1 brew install maven boost-bcp rsync
 
   unpack:
     description: "Unpack boost tarball"
@@ -115,7 +100,9 @@ commands:
       - run:
           name: Unpack tarball
           command: |
-            source $BASH_ENV
+            echo BOOST_VERSION=$BOOST_VERSION
+            echo TWILIO_SUFFIX=$TWILIO_SUFFIX
+
             ./boost.sh --unpack `test -n "${BOOST_VERSION:-}" && echo --boost-version $BOOST_VERSION` \
               `test -n "${TWILIO_SUFFIX:-}" && echo --twilio-suffix -$TWILIO_SUFFIX`
           no_output_timeout: 120m
@@ -127,21 +114,23 @@ commands:
   build:
     description: "Build and Publish"
     parameters:
-      <<: *platform-parameter
-      <<: *boost-libs-parameter
-      <<: *pre-steps-parameter
+      platform:
+        description: "Platform to build"
+        type: enum
+        enum: [ headers, android, linux, linux-cxx11-abi-disabled, ios, osx ]
     steps:
       - checkout
-      - steps: << parameters.pre-steps >>
       - attach_workspace:
           at: *workspace
       - generate_build_settings
       - run:
           name: Build << parameters.platform >>
           command: |
-            source $BASH_ENV
+            echo BOOST_VERSION=$BOOST_VERSION
+            echo TWILIO_SUFFIX=$TWILIO_SUFFIX
+
             ./boost.sh -<< parameters.platform >> --no-clean --no-unpack --no-framework `test -n "${BOOST_VERSION:-}" && echo --boost-version $BOOST_VERSION` \
-              `test -n "${TWILIO_SUFFIX:-}" && echo --twilio-suffix -$TWILIO_SUFFIX` --boost-libs "<< parameters.boost-libs >>"
+              `test -n "${TWILIO_SUFFIX:-}" && echo --twilio-suffix -$TWILIO_SUFFIX` --boost-libs "<< pipeline.parameters.boost-libs >>"
           no_output_timeout: 120m
       - persist_to_workspace:
           root: .
@@ -152,60 +141,45 @@ commands:
 
 jobs:
   unpack-sources:
-    executor: linux-executor
+    executor:
+      name: linux-executor
+      resource-class: small
     steps:
       - run:
           name: apt install
-          command: apt -y --no-install-recommends install libboost-tools-dev rsync
+          command: |
+            apt-get -y update
+            apt-get -y --no-install-recommends install libboost-tools-dev
       - unpack
 
-  build-headers:
-    executor: linux-executor
+  build-on-linux:
+    parameters:
+      platform:
+        type: enum
+        enum: [ headers, linux, linux-cxx11-abi-disabled, android ]
+    executor:
+      name: linux-executor
+      resource-class: medium+
     steps:
       - build:
-          platform: headers
+          platform: << parameters.platform >>
 
-  build-linux:
-    executor: linux-executor
+  build-on-mac:
+    parameters:
+      platform:
+        type: enum
+        enum: [ osx, ios ]
+    executor: mac-executor
     steps:
+      - install_mac_buildtools
       - build:
-          platform: linux
-
-  build-linux-cxx11-abi-disabled:
-    executor: linux-executor
-    steps:
-      - build:
-          platform: linux-cxx11-abi-disabled
-
-  build-android:
-    executor: android-executor
-    steps:
-      - build:
-          platform: android
-
-  build-osx:
-    executor: macos-ios-executor
-    steps:
-      - build:
-          platform: osx
-          pre-steps:
-            - prepare_macos_ios:
-                cache-tag: xcode12
-
-  build-ios:
-    executor: macos-ios-executor
-    steps:
-      - build:
-          platform: ios
-          pre-steps:
-            - prepare_macos_ios:
-                cache-tag: xcode12
+          platform: << parameters.platform >>
 
   deploy-artifactory:
-    executor: linux-executor
     description: "Deploy binaries to artifactory"
-    parameters:
-      <<: *boost-libs-parameter
+    executor:
+      name: linux-executor
+      resource-class: small
     steps:
       - checkout
       - attach_workspace:
@@ -216,62 +190,43 @@ jobs:
           command: echo "$ARTIFACTORY_SETTINGS" | base64 --decode > artifactory-settings.xml
       - run:
           name: Deploy binaries to artifactory
+          no_output_timeout: 120m
           command: |
             source $BASH_ENV
             ./boost.sh --no-clean --no-unpack --no-framework --deploy `test -n "${BOOST_VERSION:-}" && echo --boost-version $BOOST_VERSION` \
-              `test -n "${TWILIO_SUFFIX:-}" && echo --twilio-suffix -$TWILIO_SUFFIX` --boost-libs "<< parameters.boost-libs >>"
-          no_output_timeout: 120m
+              `test -n "${TWILIO_SUFFIX:-}" && echo --twilio-suffix -$TWILIO_SUFFIX` --boost-libs "<< pipeline.parameters.boost-libs >>"
 
 workflows:
-  version: 2
   build-and-deploy:
     jobs:
       - unpack-sources:
           <<: *ignore-master
           name: unpack
           context: dockerhub-pulls
-      - build-headers:
+
+      - build-on-linux:
           <<: *ignore-master
-          name: build-boost-headers
+          name: build-boost-<< matrix.platform >>
           context: dockerhub-pulls
           requires:
             - unpack
-      - build-android:
+          matrix:
+            parameters:
+              platform: [ headers, linux, linux-cxx11-abi-disabled, android ]
+
+      - build-on-mac:
           <<: *ignore-master
-          name: build-boost-android
-          context: dockerhub-pulls
+          name: build-boost-<< matrix.platform >>
           requires:
             - unpack
-      - build-linux:
-          <<: *ignore-master
-          name: build-boost-linux
-          context: dockerhub-pulls
-          requires:
-            - unpack
-      - build-linux-cxx11-abi-disabled:
-          <<: *ignore-master
-          name: build-boost-linux-cxx11-abi-disabled
-          context: dockerhub-pulls
-          requires:
-            - unpack
-      - build-ios:
-          <<: *ignore-master
-          name: build-boost-ios
-          requires:
-            - unpack
-      - build-osx:
-          <<: *ignore-master
-          name: build-boost-osx
-          requires:
-            - unpack
+          matrix:
+            parameters:
+              platform: [ ios, osx ]
+
       - deploy-artifactory:
           <<: *only-release-tags
           name: deploy
           context: dockerhub-pulls
           requires:
-            - build-boost-headers
-            - build-boost-android
-            - build-boost-linux
-            - build-boost-linux-cxx11-abi-disabled
-            - build-boost-ios
-            - build-boost-osx
+            - build-on-linux
+            - build-on-mac
